version: "3"
services:
  api-server:
    image: api-server
    ports:
      - "3030:3000"
    networks:
      - finance-app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27018:27017"
    networks:
      - finance-app
    volumes:
      - mongo-data:/data/db
networks:
  finance-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
